/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Step model module.
* @module model/Step
* @version v0
*/
export default class Step {
    /**
    * Constructs a new <code>Step</code>.
    * @alias module:model/Step
    * @class
    */


    /**
    * Constructs a <code>Step</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Step} obj Optional instance to populate.
    * @return {module:model/Step} The populated <code>Step</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Step();
                        
            
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('imageURL')) {
                obj['imageURL'] = ApiClient.convertToType(data['imageURL'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {String} imageURL
    */
    'imageURL' = undefined;




}
