/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Nutrient model module.
* @module model/Nutrient
* @version v0
*/
export default class Nutrient {
    /**
    * Constructs a new <code>Nutrient</code>.
    * @alias module:model/Nutrient
    * @class
    * @param name {String} 
    */

    constructor(name) {
        
        
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>Nutrient</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Nutrient} obj Optional instance to populate.
    * @return {module:model/Nutrient} The populated <code>Nutrient</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Nutrient();
                        
            
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} uuid
    */
    'uuid' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {module:model/Nutrient.CategoryEnum} category
    */
    'category' = undefined;



    /**
    * Allowed values for the <code>category</code> property.
    * @enum {String}
    * @readonly
    */
    static CategoryEnum = {
        /**
         * value: "CARBOHYDRATES"
         * @const
         */
        "CARBOHYDRATES": "CARBOHYDRATES",
        /**
         * value: "PROTEIN"
         * @const
         */
        "PROTEIN": "PROTEIN",
        /**
         * value: "FAT"
         * @const
         */
        "FAT": "FAT",
        /**
         * value: "VITAMINS"
         * @const
         */
        "VITAMINS": "VITAMINS",
        /**
         * value: "MINERALS"
         * @const
         */
        "MINERALS": "MINERALS",
        /**
         * value: "WATER"
         * @const
         */
        "WATER": "WATER"    };

}
